apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
      app: webmvc
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: webmvc
  name: webmvc
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: webmvc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: webmvc
    spec:
      containers:
        - image: 2kmiguel64/frontend-calendar
          name: webmvc
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
